[package]
name = "messaging_thread_pool"
version = "0.1.0"
authors = ["cainem"]
edition = '2021'
description = "A library for a aiding the creation of a thread pool that communicates via channels"
license = "MIT"

[dependencies]
tracing = { version = "0.1.36", features = [ "max_level_trace", "release_max_level_trace" ] }
tracing-subscriber = { version = "0.3.15", features = [ "fmt", "std", "json"] }
tracing-attributes = "0.1.22"
tracing-appender = "0.2.2"
backtrace = "0.3.66"
crossbeam-channel = "0.5.6"
rand = "0.8.5"
arrayvec = "0.7.2"
rand_xoshiro = "0.6.0"
once_cell = "1.15.0"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "element_creation"
harness = false


